shared:
  common: &common_checks
    - check-success = amd64
    - check-success = build
    - check-success = codeql (actions)
    - check-success = codeql (javascript)
    - check-success = codeql (typescript)
    - check-success = dependency-review
    - check-success = format
    - check-success = gitleaks
    - check-success = lint
    - check-success = playwright-tests
    - check-success = renovate
    - check-success = unit-testing
    - check-success = zizmor
    - or:
        - check-success = renovate/stability-days
        - check-pending != renovate/stability-days

merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind = 0"
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"

pull_request_rules:
  - name: automatic approval
    conditions:
      - author != renovate[bot]
      - and: *common_checks
    actions:
      review:
        type: APPROVE
        message: "Automatically approving {{ author }}"

  - name: automatic approval for Renovate pull requests
    conditions:
      - author = renovate[bot]
      - and: *common_checks
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate

  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      # - author != renovate[bot]
      - "#approved-reviews-by>=1"
      - and: *common_checks
    actions:
      merge:
        method: merge

  - name: automatic deletion of head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
