services:
  mongo:
    image: mongo:latest@sha256:4a73a96a9a161bd3a220c22be5d989065567543c952f2a17ff764075171629ca
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
