name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      mongo:
        image: mongo:8@sha256:f071cbf97a6e52fb7f07ce9ca5d862ad79876bf0eba9ba97758337d740449638
        ports:
          - 27017:27017
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: generate sw
        run: pnpm run generate.sw

      - name: Build
        run: pnpm build
        env:
          # temporary
          MAPBOX_API_TOKEN: ""
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          DATABASE_URI: ${{ vars.DATABASE_URI }}
          NEXT_PUBLIC_SERVER_URL: ${{ vars.NEXT_PUBLIC_SERVER_URL }}
